### ISSUE TITLE
GPU utilisation is suspiciously low during self-play

### ISSUE THREAD

**Issue by Mitchell-Faas** [tensorflow/minigo#257] opened 2018-06-05 09:29 UTC
I realise that this is not for people needing a tutorial about how to get minigo to work, but after setting everything up and letting the program play games / train itself, I've noticed how self-play is barely using any resources. Because of that, I should be able to run many parallel self-play games to speed up the process. I have not however been able to identify a built in option to achieve this, which leads me to ask:
Does this option exist somewhere, or is the program designed to be ran in multiple instances instead?

**Comment by amj** [comment] 2018-06-05 16:48
there aren't flags to run multiple games in parallel.  Some of the work in #256 is headed that way but it's not on yet.

instead, as you pointed out, the program is designed to be run with multiple instances; you'll mostly be constrained by gpu ram.

**Comment by tommadams** [comment] 2018-06-07 03:09
Wow, I don't remember actually closing this issue... not sure how that happened.

When you say that self-play is barely using any resources, do you mean CPU only or GPU? Self-play is heavily bottlenecked by the GPU and locally on my machine I get > 95% GPU utilization. So running more games in parallel won't likely make a significant difference to performance on my machine.

That said, we are working on adding support for playing multiple games in parallel in the coming weeks.

**Comment by Mitchell-Faas** [comment] 2018-06-07 09:51
I mean GPU. When minigo self-plays, my GPU utilization looks something like this: https://i.imgur.com/N9sGVnQ.png

It might be possible that I set something up wrong, but training does fully utilise the GPU.

**Comment by amj** [comment] 2018-06-07 17:22
wow, yeah, something looks kinda off there.  Are you running 9x9s or 19x19s?

**Comment by Mitchell-Faas** [comment] 2018-06-10 22:57
Anyone have any ideas on how to get the GPU utilisation up, or things I might've done wrong?

**Comment by tommadams** [comment] 2018-06-14 21:07
I'm unable to reproduce this problem I'm afraid.
I upgraded the GPU in my desktop to a quadro m2000 and I still see > 95% utilization.

**Comment by sethtroisi** [comment] 2018-06-16 17:51
Might be a windows bug, see related LZ issue: https://github.com/gcp/leela-zero/issues/735

GCP suggested "On the Windows task manager, with an NVIDIA card, you can switch what the GPU usage graphs show. If you switch it to "Compute_0", you will see that the card is in fact 100% loaded."

**Comment by Mitchell-Faas** [comment] 2018-06-16 18:20
I have not been able to find the compute_0 option, but I'm fine assuming that this is what's going on 👍

**Closed** 2018-09-26 18:02 UTC
