### ISSUE TITLE
[CC] Broken documentation

### ISSUE THREAD

**Issue by sethtroisi** [tensorflow/minigo#369] opened 2018-08-11 09:03 UTC
` bazel-bin/cc/main --model=$MODEL_PATH`
=>
`Unrecognized mode ""`
_____

`bazel-bin/cc/main --mode gtp --engine=remote --model=$MODEL_PATH`
=>
`
  File "inference_worker.py", line 70
    print = functools.partial(print, file=sys.stderr, flush=True)
          ^
SyntaxError: invalid syntax
`

This might be fixed by #366 which modifies this line.

_____

`bazel-bin/cc/main --mode gtp --engine=tf --model=$MODEL_PATH`
```2018-08-11 01:55:09.129359: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-08-11 01:55:09.129820: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1356] Found device 0 with properties: 
name: GeForce GTX 970 major: 5 minor: 2 memoryClockRate(GHz): 1.2155
pciBusID: 0000:01:00.0
totalMemory: 3.93GiB freeMemory: 2.39GiB
2018-08-11 01:55:09.129837: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1435] Adding visible gpu devices: 0
2018-08-11 01:55:09.674420: I tensorflow/core/common_runtime/gpu/gpu_device.cc:923] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-08-11 01:55:09.674454: I tensorflow/core/common_runtime/gpu/gpu_device.cc:929]      0 
2018-08-11 01:55:09.674461: I tensorflow/core/common_runtime/gpu/gpu_device.cc:942] 0:   N 
2018-08-11 01:55:09.675113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1053] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2094 MB memory) -> physical GPU (device: 0, name: GeForce GTX 970, pci bus id: 0000:01:00.0, compute capability: 5.2)
2018-08-11 01:55:09.676153: F cc/dual_net/tf_dual_net.cc:96] Non-OK-status: session_->Run(inputs_, output_names_, {}, &outputs_) status: Invalid argument: Session was not created with a graph before Run()!
Aborted (core dumped)
```

**Comment by amj** [comment] 2018-09-04 20:27
dupe of #371  ?

**Comment by amj** [comment] 2019-02-14 05:06
closed obsolete

**Closed by amj** 2019-02-14 05:06 UTC
