### ISSUE TITLE
Should do cycle detection/superko

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#235] opened 2018-05-16 18:38 UTC
i.e. triple kos.

**Comment by sethtroisi** [comment] 2018-05-16 18:45
if you have local sgfs...

find sgf/ -wholename '*/clean/*sgf' | tqdm > clean_sgfs
< clean_sgfs parallel -m -l100 sgfcheck |& tee results
grep -v 'cycle' results

I think it's 48,000 out of 2666000 games or 1.8% of games

**Comment by sethtroisi** [comment] 2018-05-16 18:47
Most of there are not triple kos and instead are https://senseis.xmp.net/?SendingTwoReturningOne

**Comment by brilee** [comment] 2018-09-27 04:38
dupe of #8

**Closed by brilee** 2018-09-27 04:38 UTC
