### ISSUE TITLE
How to automatically adjust the resign threshold?

### ISSUE THREAD

**Issue by amj** [tensorflow/minigo#73] opened 2018-02-08 00:37 UTC
- We've got a script that calculates our current false positive rate for a given threshold
 - we can parametrize the threshold for our workers by editing player_wrapper.sh
 - We don't have a way to automatically calculate the correct false positive rate, edit the value in player_wrapper.sh, and then rebuild the image.

Alternate idea: We could also automatically calculate the correct false positive rate, stick it in a file, and have the workers read the file.

**Comment by brilee** [comment] 2018-02-08 04:37
Rebuilding an image just to push new hyperparameters sounds heavyweight. I like the idea of having a file on GCS that has operating hyperparameters (resign threshold, etc.), so that as soon as a worker exits, it automatically picks up the latest hyperparameters the same way it picks up the latest model.

**Comment by brilee** [comment] 2018-02-08 04:38
(We are slowly reinventing the database here)

**Comment by amj** [comment] 2018-02-08 04:47
haha, i have had a similar thought XD

**Comment by brilee** [comment] 2018-02-20 21:04
Closing as dupe of https://github.com/tensorflow/minigo/issues/61

**Closed by brilee** 2018-02-20 21:04 UTC
